import = [
    "~/.config/alacritty/themes/themes/xterm.toml"
]

[env]
  TERM = "tmux-256color"

[font]
  normal = { family = "MesloLGS Nerd Font", style = "Regular" }
  bold = { family = "MesloLGS Nerd Font", style = "Bold" }
  italic = { family = "MesloLGS Nerd Font", style = "Italic" }
  bold_italic = { family = "MesloLGS Nerd Font", style = "Bold Italic" }
  builtin_box_drawing = true
  size = 12

[keyboard]
  bindings = [
    # { key = "Q", mods = "Command", action = "None"}
    # { key = "L", mods = "Control", chars = "Left"}
    # { key = "L", mods = "Control", chars = "\u0001l" },           # cmd+t           -> ctrl+a c
  ]
